---
# Configuration for detection on the nucleus segmentation dataset.
GPU_COUNT: 1
IMAGES_PER_GPU: 1

DATASET_PATH: /home/leizhou/Documents/instance_seg/data/DSB_18/
# Don't resize image during inference
IMAGE:
    RESIZE_MODE: pad64

DETECTION:
    MIN_CONFIDENCE: 0
    MAX_INSTANCES: 400
...