---
# Configuration for training on the nucleus segmentation dataset.

DEVICE: cuda:1

NAME: nuclei

NUM_CLASSES: 2

DATASET_PATH: /home/jro/wk/kaggle/input/

IMAGES_PER_GPU : 6

RPN:
    NMS_THRESHOLD: 0.9
    ANCHOR:
#        SCALES: [10, 20, 40, 60, 80]
        SCALES: [32, 64, 128, 256, 512]
        RATIOS: [0.5, 1, 2]

IMAGE:
    MAX_DIM: 512
    MEAN_PIXEL: [55.0, 55.0, 55.0]
    MIN_DIM: 512
    RESIZE_MODE: crop

PROPOSALS:
    POST_NMS_ROIS:
        INFERENCE: 2000
        TRAINING: 2000
    TRAIN_ROIS_PER_IMAGE : 128
    MAX_GT_INSTANCES: 200
...